GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/

###
GET http://localhost:3001/api/persons/1

### 
GET http://localhost:3001/api/persons/99

### POST correct
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "Lily",
  "number": "4102019"
}

### POST fail
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "",
  "number": "4102019"
}

###
DELETE http://localhost:3001/api/persons/3