GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/

###
GET http://localhost:3001/api/persons/601a0e9e08184d58c3be0256

### 
GET http://localhost:3001/api/persons/99

### POST correct
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "Colbert",
  "number": "4102019"
}

### POST fail
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "",
  "number": "4102019"
}


### PUT Bob
PUT http://localhost:3001/api/persons/601ce6924796c20a4c12c4a3
Content-Type: application/json

{
  "name": "Bob",
  "number": "00000"
}

###
DELETE http://localhost:3001/api/persons/601cda2f719f4c05dc31c70c